helm:
  parameters:
  - name: secrets.tastyAPIKey
    value: 4a13be230bmsheb288ce1350df2fp120accjsnfb31e446116f
    forcestring: false
  - name: image.name
    value: pwstaging/secrets-demo
    forcestring: true
  - name: image.tag
    value: b07e8ad6791089787ee9a09d156a874650209503
    forcestring: true
