apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque	
stringData:
  databaseUrl: "postgresql://{{ .Values.global.postgresql.postgresqlUsername}}:{{ .Values.global.postgresql.postgresqlPassword}}@{{ .Release.Name }}-postgresql:5432/healthy?schema=public"
  tastyAPIKey: "{{ .Values.secrets.tastyAPIKey }}"